### ISSUE TITLE
Question: will it work on Acer Nitro 5 AN515-42?

### ISSUE THREAD

**Issue by Benman2785** [ysc3839/NitroFans4Afterburner#1]
is it safe to test on AN515-42?

**Comment by ysc3839** [comment]
I don't know. I should work if all Nitro series laptop use the same NitroSense. The communication protocol is decompiled from a version of NitroSense given by my friend. And it's working on my friend's laptop.
But I can't guarantee it's safe. The underlying interface is implemented in [ACPI SSDT](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/acpi-system-description-tables#differentiated-system-description-table-dsdt), which has full access to hardware and memory. So if there's bug in SSDT code, passing wrong data to it may cause problems.
